"""Constants used in pyhs3."""

DEFAULT_HTTP_PORT = 80
DEFAULT_USERNAME = 'default'
DEFAULT_PASSWORD = 'default'
DEFAULT_HTTP_TIMEOUT = 3
DEFAULT_ASCII_PORT = 11000

DEVICE_ZWAVE_BATTERY = 'Z-Wave Battery'
DEVICE_ZWAVE_CENTRAL_SCENE = 'Z-Wave Central Scene'
DEVICE_ZWAVE_DOOR_LOCK = 'Z-Wave Door Lock'
DEVICE_ZWAVE_SENSOR_BINARY = 'Z-Wave Sensor Binary'
DEVICE_ZWAVE_SWITCH = 'Z-Wave Switch'
DEVICE_ZWAVE_SWITCH_BINARY = 'Z-Wave Switch Binary'
DEVICE_ZWAVE_SWITCH_MULTILEVEL = 'Z-Wave Switch Multilevel'

REASON_DISCONNECTED = 'disconnected'
REASON_RECONNECTED = 'reconnected'

STATE_CONNECTING = 'connecting'
STATE_DISCONNECTED = 'disconnected'
STATE_IDLE = 'idle'
STATE_LISTENING = 'listening'
STATE_STOPPED = 'stopped'
