"""Helper constants for Home Assistant."""

from .const import (DEVICE_ZWAVE_BATTERY, DEVICE_ZWAVE_CENTRAL_SCENE, DEVICE_ZWAVE_DOOR_LOCK,
                    DEVICE_ZWAVE_SENSOR_BINARY, DEVICE_ZWAVE_SWITCH, DEVICE_ZWAVE_SWITCH_BINARY,
                    DEVICE_ZWAVE_SWITCH_MULTILEVEL)


HASS_BINARY_SENSORS = [DEVICE_ZWAVE_SENSOR_BINARY]
HASS_LIGHTS = [DEVICE_ZWAVE_SWITCH_MULTILEVEL]
HASS_LOCKS = [DEVICE_ZWAVE_DOOR_LOCK]
HASS_SENSORS = [DEVICE_ZWAVE_BATTERY]
HASS_SWITCHES = [DEVICE_ZWAVE_SWITCH, DEVICE_ZWAVE_SWITCH_BINARY]
HASS_EVENTS = [DEVICE_ZWAVE_CENTRAL_SCENE]
